/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco-Pc
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {  
        initComponents();
      // this.setSize(380, 370);
         this.setLocationRelativeTo(null);
        this.setLayout(new BorderLayout());
    }
    public void OpenUnach(){
    
    try{Desktop.getDesktop().browse(URI.create("http://www.unach.edu.ec/"));
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, e);
    }
    
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMinimizat = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lblUnach = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(663, 379));
        setMaximumSize(new java.awt.Dimension(663, 379));
        setMinimumSize(new java.awt.Dimension(663, 379));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(663, 379));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsuario.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 90, -1));

        lblContraseña.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblContraseña.setText("Password");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 120, -1));

        txtUsuario.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 0, 51));
        txtUsuario.setText("Ingrese usuario");
        txtUsuario.setBorder(null);
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 160, 20));

        btnIngresar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 100, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/555wSrXU_400x400.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 380));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 130, 40));

        lblMinimizat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMinimizat.setForeground(new java.awt.Color(0, 0, 51));
        lblMinimizat.setText("  -");
        lblMinimizat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizatMouseClicked(evt);
            }
        });
        getContentPane().add(lblMinimizat, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 20, 20));

        lblExit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblExit.setForeground(new java.awt.Color(0, 0, 51));
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        getContentPane().add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        password.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 51));
        password.setText("jPasswordField1");
        password.setBorder(null);
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 160, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 260, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 260, 10));

        lblUnach.setText("http://www.unach.edu.ec/");
        lblUnach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUnach.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblUnachMouseMoved(evt);
            }
        });
        lblUnach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUnachMouseClicked(evt);
            }
        });
        getContentPane().add(lblUnach, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
         String Usuario="f";
         String Contraseña="123";
       
       String Pass = new String(password.getPassword());
       if(txtUsuario.getText().equals(Usuario)&& Pass.equals(Contraseña)){
           
           MenuPrincipal GN= new MenuPrincipal();
           GN.setVisible(true);
           dispose();
           
       }else{
           JOptionPane.showMessageDialog(this, "Usuario / Contraseña incorrecta");
       }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        // TODO add your handling code here:
        txtUsuario.setText(""); 
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        // TODO add your handling code here:
         password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void lblMinimizatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizatMouseClicked
        // TODO add your handling code here:
        this.setState(login.ICONIFIED);
    }//GEN-LAST:event_lblMinimizatMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        int dialoogoButton=JOptionPane.YES_NO_OPTION;
       int result =JOptionPane.showConfirmDialog(null,"Deseas salir del login?","EXIT",dialoogoButton);
        if(result ==0)
        {System.exit(0);
        }
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblUnachMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnachMouseMoved
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_lblUnachMouseMoved

    private void lblUnachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUnachMouseClicked
        // TODO add your handling code here:
        OpenUnach();
    }//GEN-LAST:event_lblUnachMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimizat;
    private javax.swing.JLabel lblUnach;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
